config/routes.rb
Obra::Application.routes.draw do
  resources :proprietarios

end

app/models/proprietario.rb
class Proprietario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/proprietarios_controller.rb
class ProprietariosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proprietarios_helper.rb
module ProprietariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obra</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/proprietarios/_form.html.erb
<%= form_for(@proprietario) do |f| %>
  <% if @proprietario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proprietario.errors.count, "error") %> prohibited this proprietario from being saved:</h2>

      <ul>
      <% @proprietario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :rua %><br>
    <%= f.text_field :rua %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :complemento %><br>
    <%= f.text_field :complemento %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proprietarios/edit.html.erb
<h1>Editing proprietario</h1>

<%= render 'form' %>

<%= link_to 'Show', @proprietario %> |
<%= link_to 'Back', proprietarios_path %>

app/views/proprietarios/index.html.erb
<h1>Listing proprietarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Sexo</th>
      <th>Rua</th>
      <th>Numero</th>
      <th>Complemento</th>
      <th>Cpf</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @proprietarios.each do |proprietario| %>
      <tr>
        <td><%= proprietario.nome %></td>
        <td><%= proprietario.idade %></td>
        <td><%= proprietario.sexo %></td>
        <td><%= proprietario.rua %></td>
        <td><%= proprietario.numero %></td>
        <td><%= proprietario.complemento %></td>
        <td><%= proprietario.cpf %></td>
        <td><%= link_to 'Show', proprietario %></td>
        <td><%= link_to 'Edit', edit_proprietario_path(proprietario) %></td>
        <td><%= link_to 'Excluir', proprietario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proprietario', new_proprietario_path %>

app/views/proprietarios/new.html.erb
<h1>New proprietario</h1>

<%= render 'form' %>

<%= link_to 'Back', proprietarios_path %>

app/views/proprietarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @proprietario.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @proprietario.idade %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @proprietario.sexo %>
</p>

<p>
  <strong>Rua:</strong>
  <%= @proprietario.rua %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @proprietario.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @proprietario.complemento %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @proprietario.cpf %>
</p>

<%= link_to 'Edit', edit_proprietario_path(@proprietario) %> |
<%= link_to 'Back', proprietarios_path %>